services:
  abuse-detector:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ABUSE_API_VERSION: ${TAG}
    image: ${IMAGE}:${TAG}
    ports:
      - "8000:8000"
    environment:
      - ABUSE_API_DEBUG=false
      - ABUSE_API_REDIS_ENABLED=false
      - ABUSE_API_MODEL_CACHE_DIR=/app/models
      - ABUSE_API_DEVICE=cpu
    volumes:
      - model_cache:/app/models
      - ./lexicons:/app/lexicons
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - with-redis

volumes:
  redis_data:
  model_cache: